export const CHANGE_SELECTED_TAB = "CHANGE_SELECTED_TAB";
export const ADD_LAYER = "ADD_LAYER"
export const REMOVE_LAYER = "REMOVE_LAYER";
export const EDIT_LAYER = "EDIT_LAYER";
export const CURRENT_LAYER_EDITING = "CURRENT_LAYER_EDITING";
export const TOGGLE_ADD_LAYER_POPUP = "TOGGLE_ADD_LAYER_POPUP";
export const TOGGLE_EDIT_LAYER_POPUP = "TOGGLE_EDIT_LAYER_POPUP";
export const ADD_LAYER_IMAGES = "ADD_LAYER_IMAGES";